name: Publish Docker Image

on:
  push:
    branches:
      - "main"
  tags:
    - ghcr.io/propek/rehlds-cstrike:*

env:
  ARCHITECTURES: linux/amd64
  IMAGE_NAME: rehlds-cstrike
  IMAGE_NAMESPACE: propek

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.ARCHITECTURES }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker tag
        id: docker_tag
        run: |
          if [[ startsWith("${{ github.ref }}", "refs/tags/") ]]; then
            echo "::set-output name=tag::${{ github.ref_name }}"
          else
            echo "::set-output name=tag::${{ github.sha }}" # Use SHA for branches
          fi

      - id: metadata
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            ghcr.io/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{major}}.{{minor}},enable=true # Only for tags
            type=semver,pattern=latest,enable=true # Only for tags
            type=edge,branch=main # Optional: Tag with branch name if needed

      - uses: docker/build-push-action@v5.1.0
        with:
          context: .
          platforms: ${{ env.ARCHITECTURES }}
          push: true
          file: Dockerfile
          provenance: false
          tags: ghcr.io/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ steps.docker_tag.outputs.tag }}
          labels: ${{ steps.metadata.outputs.labels }}
