name: Publish Docker Image

on:
  push:
    branches:
      - "main"
    tags:
      - ghcr.io/propek/rehlds-cstrike:*

env:
  ARCHITECTURES: linux/amd64
  IMAGE_NAME: rehlds-cstrike
  IMAGE_NAMESPACE: propek

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.ARCHITECTURES }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: metadata
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            ghcr.io/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{major}}.{{minor}},enable=true
            type=semver,pattern=latest,enable=true
            type=edge,branch=main
          sha: ${{ github.sha }}
      - uses: docker/build-push-action@v5.1.0
        with:
          context: .
          platforms: ${{ env.ARCHITECTURES }}
          push: true
          file: Dockerfile
          provenance: false
          tags: ${{ steps.metadata.outputs.tags }},ghcr.io/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ steps.metadata.outputs.sha }}
          labels: ${{ steps.metadata.outputs.labels }}
